# Mathematics in Machine Learning

To better understand the theory behind Machine Learning algorithms, which are prevalent in the Data Science field, one must know the concepts of Linear Algebra.

This is a field of mathematics applied in many fields of study, since it allows us to efficiently model concepts.

In this notebook, we will explore basic linear algebra terms and phenomena, in the eyes of a computer scientist.

## Scalars and Vectors

A scalar is a single number, often representing a quantity or measurement (for example, 24). Scalars are the simplest form of data in linear algebra and are used extensively in machine learning to represent weights, biases, and other parameters.

A vector is an ordered list of numbers, which can be thought of as a point in a multi-dimensional space. Vectors are fundamental in machine learning as they are used to represent data points, feature sets, and gradients. 

In python, using the numpy library, it is simple to define vectors and do operations using scalars and other vectors:

In [8]:
import numpy as np

a1 = np.ones(10)
print("Vector of 10 ones:\n", a1)

a2 = np.linspace(3, 15, 10)
print("\n Vector of 10 numbers that have the same distance from each other, starting with 3 and ending with 15:\n", a2)

a3 = np.random.rand(10)
print("\n Vector of 10 random numbers between [0, 1):\n", a3)

a4 = np.random.randint(1, 10, size=10)
print("\n Vector of 10 random numbers between [1, 10):\n", a4)

Vector of 10 ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 Vector of 10 numbers that have the same distance from each other, starting with 3 and ending with 15:
 [ 3.          4.33333333  5.66666667  7.          8.33333333  9.66666667
 11.         12.33333333 13.66666667 15.        ]

 Vector of 10 random numbers between [0, 1):
 [0.77916405 0.61112608 0.657783   0.91928666 0.48682244 0.55796896
 0.74189646 0.98869585 0.29680354 0.34892569]

 Vector of 10 random numbers between [1, 10):
 [3 2 9 3 3 2 5 7 9 4]


In [9]:
a1 = np.array([1, 2, 3, 4])

print("Vector a1:\n", a1)

print("\nAdding the scalar 2 to the vector a1:\n", a1 + 2)

print("\nSubtract a scalar of value 1 to the vector.\n", a1 - 1)

print("\nMultiply the vector with a scalar of value 10:\n", a1 * 10)

print("\nDivide the vector by a scalar of value 5:\n", a1 / 5)

Vector a1:
 [1 2 3 4]

Adding the scalar 2 to the vector a1:
 [3 4 5 6]

Subtract a scalar of value 1 to the vector.
 [0 1 2 3]

Multiply the vector with a scalar of value 10:
 [10 20 30 40]

Divide the vector by a scalar of value 5:
 [0.2 0.4 0.6 0.8]


## Matrices and Tensors

Matrices and tensors are higher-dimensional generalizations of vectors and are crucial in the field of machine learning.

### Matrices

A matrix is a two-dimensional array of numbers, which can be thought of as a collection of vectors. Matrices are used extensively in machine learning to represent datasets, transformation operations, and more. For example, in supervised learning, a dataset is often represented as a matrix where each row corresponds to a data point and each column corresponds to a feature.

In python, using the numpy library, it is simple to define matrices and perform operations on them, using matrices, vectors and scalars:

In [12]:
# Define matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

# Matrix addition
matrix_sum = matrix1 + matrix2
print("\nSum of Matrix 1 and Matrix 2:\n", matrix_sum)

# Matrix subtraction
matrix_diff = matrix1 - matrix2
print("\nDifference of Matrix 1 and Matrix 2:\n", matrix_diff)

# Element-wise multiplication
matrix_product = matrix1 * matrix2
print("\nElement-wise multiplication of Matrix 1 and Matrix 2:\n", matrix_product)

# Matrix dot product
matrix_dot_product = np.dot(matrix1, matrix2)
print("\nDot product of Matrix 1 and Matrix 2:\n", matrix_dot_product)

# Scalar multiplication
scalar = 2
matrix_scalar_product = matrix1 * scalar
print("\nMatrix 1 multiplied by scalar 2:\n", matrix_scalar_product)

# Matrix-vector multiplication
vector = np.array([1, 2, 3])
matrix_vector_product = np.dot(matrix1, vector)
print("\nMatrix 1 multiplied by vector [1, 2, 3]:\n", matrix_vector_product)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of Matrix 1 and Matrix 2:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Difference of Matrix 1 and Matrix 2:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise multiplication of Matrix 1 and Matrix 2:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Dot product of Matrix 1 and Matrix 2:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix 1 multiplied by scalar 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix 1 multiplied by vector [1, 2, 3]:
 [14 32 50]


### Tensors

A tensor is a multi-dimensional array of numbers. Depending on the number of indexes, they can be a vector (1 index), matrix (2 indexes), and beyond the third-order tensors (3 indexes, where the 1st points to the row, 2nd to the column and 3rd to the axis), we have higher-order tensors. This makes them a generalization of the previous concepts. This is important for machine learning porpouses because:

1. **Data Representation**: Tensors are used to represent data in machine learning. For example, a color image can be represented as a 3-dimensional tensor with dimensions corresponding to height, width, and color channels (RGB).

2. **Model Parameters**: In neural networks, tensors are used to represent the weights and biases of the model. These parameters are updated during the training process to minimize the loss function.

3. **Operations and Transformations**: Tensors allow for efficient mathematical operations and transformations. Libraries like TensorFlow and PyTorch are built around tensor operations, enabling efficient computation on GPUs and other hardware accelerators.

4. **Batch Processing**: Tensors enable batch processing of data, which is essential for training machine learning models. By processing multiple data points simultaneously, tensors help in speeding up the training process.

5. **Flexibility**: Tensors provide a flexible way to handle different types of data, including structured and unstructured data. This flexibility is crucial for building complex machine learning models that can handle diverse data sources.

In summary, tensors are fundamental to the field of machine learning as they provide a powerful and flexible way to represent and manipulate data and model parameters.

## Resources

https://builtin.com/data-science/basic-linear-algebra-deep-learning
https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
